robot_dimensions:
  # length and with on Studs
  length:
  width:

  # wheel diameter in mm
  wheel_diameter:

robot_motors:
  # one of (MEDIUM, LARGE)
  port_A:
  port_B:
  port_C:
  port_D:

robot sensors:
  # one of (GYRO, COLOR)
  port_1:
  port_2:
  port_3:
  port_4:

pid_constants:
  # PID constants for the robot
  kp:
  ki:
  kd:
  accepted_error:

pid_termination_conditions:
  # PID termination conditions, set only one value and leave the other two empty
  max_iterations:
  max_time:
  max_convergence_loops:
