robot_dimensions:
  # length and width on Studs
  length_x:
  width_y:

  # wheel diameter in mm
  wheel_diameter:

mat_dimensions:
  # length and with on mm
  length_x:
  width_y:

mat_image_path:

robot_motors:
  # one of (MEDIUM, LARGE)
  port_A:
  port_B:
  port_C:
  port_D:

robot_sensors:
  # one of (GYRO, COLOR)
  port_1:
  port_2:
  port_3:
  port_4:

pid_constants:
  kp:
  ki:
  kd:


steps:
  delta_theta:
  delta_pixels:
  additional_motors_steps:
  speed_steps:

robot_movement_configurations:
  # if the LARGE motors positive movement is forward, bool (True, False)
  large_motor_positive_direction:
  # if the GYRO sensor positive movement is clockwise, bool (True, False)
  gyro_positive_direction:
